/**
 * What actually drew a published card, kept after review is over (#75).
 *
 * ── The gap this closes ──────────────────────────────────────────────────────
 * A published card records `provider` in `seed/cards.json` — the LANE. #64 proved
 * that is not the same thing as the model: a request for `flux` came back served
 * by `sana`, silently, with no version string anywhere but a response header. So
 * `provider: "pollinations"` does not explain why a theme's art looks the way it
 * does, and does not let anyone reproduce a bake-off.
 *
 * The witness exists — `generate()` returns `model` and `--review` writes it to a
 * sidecar beside every candidate (`review-files.ts`) — but `seed/review/` is
 * gitignored scratch. It dies at publish. This is where the picked candidate's
 * sidecar goes to survive.
 *
 * ── Why git and not the `cards` table ────────────────────────────────────────
 * The `cards` table was the other candidate: provenance would land on the row it
 * describes and never touch the authoring surface. It loses on three counts.
 *
 *   - The rest of the record is already in git. The prompt is in
 *     `seed/cards.json`, `ART_STYLE` is in `prompt.ts`, the parameter bag is in
 *     the adapter. Only the witness is homeless. Splitting one record across git
 *     and Postgres means answering one question needs a psql session against
 *     production, about art that has nothing to do with production.
 *   - Git is this project's durable half. `docs/RESTORE.md` §4 puts the pool's
 *     art outside what a `pg_dump` can restore, and artifact retention caps the
 *     backups at 90 days; a record in the database is exactly as recoverable as
 *     the thing it explains, which is to say not.
 *   - A wrong row is undetectable. A wrong file is a diff, in the same pull
 *     request that ships the theme.
 *
 * It is NOT written into `seed/cards.json`, for that file's own reason: it is
 * hand-authored and schema-validated, and a tool writing generated fields into it
 * changes what it is. This file is generated and only generated — nobody hand-
 * edits it, and the runbook says so.
 *
 * ── The honesty rule, and the providers that witness nothing ─────────────────
 * `model` is what the response NAMED. Cloudflare SDXL names nothing (#65), so its
 * record carries `model: null`. It is never back-filled from `params.model`: that
 * is what was ASKED FOR, it is recorded separately and completely, and a field
 * that is a witness for one provider and a guess for another is worse than no
 * field — #67 kept `model` optional for exactly this reason.
 *
 * `null` is written explicitly rather than left off. On disk in scratch an absent
 * key is fine, because the contact sheet renders "model not reported" beside it;
 * in a committed record read a year later, an absent key is indistinguishable
 * from a writer that forgot. So the schema requires it.
 *
 * ── What it does NOT touch ───────────────────────────────────────────────────
 * `reviewKey`. The witness arrives with the RESPONSE, and `reviewKey` names the
 * file the request will be written to — it is computed before there is anything
 * to witness. Provenance therefore embeds the reviewKey and never feeds it. That
 * direction is one-way by construction, not by convention: nothing in this module
 * is an input to `keys.ts` or `review-files.ts`.
 *
 * And it never blocks a publish. Provenance is a record, not a guarantee; FR9 is
 * the guarantee. A card whose sidecar is missing is published and reported, not
 * refused — a record that can stop a card reaching a child is a new way for a
 * child's binder to be empty.
 */
import { z } from "zod";
import type { ReviewSidecar } from "./review-files";

/**
 * Written into the file on every save, because JSON cannot carry a comment and
 * this file is missing ~360 cards for a reason a reader deserves on sight.
 */
export const PROVENANCE_README =
  "Generated by `pnpm seed --sync` / `--publish` — never hand-edited. One entry per card " +
  "published since #75, holding the picked bake-off candidate's sidecar: `model` is what the " +
  "response NAMED (null when the provider names nothing, e.g. cloudflare-sdxl), `params` is what " +
  "was ASKED FOR, and `reviewKey` content-addresses the bytes by prompt+ART_STYLE hash and " +
  "parameter hash. `reviewed: false` means the bytes were generated at publish time under " +
  "--allow-unreviewed and no human ever saw them. Cards published before #75 are absent and stay " +
  "absent: their review files are gone and inventing entries would be fabrication. See " +
  "src/features/pool/provenance.ts.";

const cardProvenanceSchema = z.object({
  /** Registered adapter that drew the published bytes. */
  provider: z.string().min(1),
  /** What the response NAMED. `null` means the provider witnessed nothing. */
  model: z.string().min(1).nullable(),
  /** What was ASKED FOR — the adapter's total, hashed parameter bag. */
  params: z.record(z.union([z.string(), z.number(), z.boolean()])),
  /** Encoded format of the published bytes, sniffed at generation time. */
  format: z.string().min(1),
  /** `<theme>-<card>-<promptHash8>-<providerId>-<paramHash4>` — the bytes' content address. */
  reviewKey: z.string().min(1),
  /**
   * Did a human see these bytes before a child did?
   *
   * True for everything the runbook produces: `--sync` publishes a candidate off
   * `seed/review/` that was screened at checkpoint 2. False only on the
   * `--allow-unreviewed` path, which generates at publish time — there the
   * `reviewKey` is a correct content address for bytes that were never in a
   * review folder and never in front of anyone.
   *
   * Recorded rather than left implicit because the warning that flag prints
   * scrolls past, and this file is the only thing that outlives the run. FR9 is
   * still the guarantee; this is its receipt.
   */
  reviewed: z.boolean(),
});

const provenanceFileSchema = z.object({
  /** theme name -> card name -> record. Nested rather than keyed by a composite
   * string: `"A / B" + "C"` and `"A" + "B / C"` would collide, the same trap
   * `publish-plan.ts` uses a NUL separator to avoid — and a NUL in a JSON key
   * would make this file unreadable to the human it exists for. */
  themes: z.record(z.record(cardProvenanceSchema)),
});

export type CardProvenance = z.infer<typeof cardProvenanceSchema>;
export type ProvenanceFile = z.infer<typeof provenanceFileSchema>;

/** One card whose bytes this run published, with the record for them. */
export interface PublishedCard {
  theme: string;
  card: string;
  provenance: CardProvenance;
}

export function emptyProvenance(): ProvenanceFile {
  return { themes: {} };
}

/**
 * Validate an already-parsed provenance file. Throws rather than falling back to
 * empty: treating an unreadable file as `{}` would clobber every record in it on
 * the next publish, which is the one failure this file cannot survive.
 *
 * The file's `readme` is not part of this type. It is a note to whoever opens
 * the file, restated on every save, so it is a serialisation concern and zod
 * drops it here rather than letting it become a field nothing reads.
 */
export function parseProvenance(json: unknown): ProvenanceFile {
  return provenanceFileSchema.parse(json);
}

/**
 * The durable record for one published candidate: its sidecar, plus the content
 * address of the bytes and whether anyone saw them.
 *
 * The sidecar is copied, never re-derived. It is what the generator observed;
 * reading today's adapter for `params` instead would record the request that
 * WOULD be made now rather than the one that was made then.
 */
export function toProvenance(
  sidecar: ReviewSidecar,
  reviewKey: string,
  reviewed: boolean,
): CardProvenance {
  return {
    provider: sidecar.provider,
    model: sidecar.model ?? null,
    params: { ...sidecar.params },
    format: sidecar.format,
    reviewKey,
    reviewed,
  };
}

/**
 * File the run's records, returning a new file (the input is left alone).
 *
 * An existing entry for the same card is REPLACED. A card is only ever recorded
 * on an INSERT, so reaching an existing entry means the card was published,
 * removed from the pool, and published again — a `--publish --reset` rebuild, or
 * a prune followed by a re-add. `blobKey` is stable and prompt-independent, so
 * that second publish overwrote the object its binder page points at. The record
 * follows the bytes; the old one describes art nobody has any more.
 */
export function recordProvenance(
  file: ProvenanceFile,
  published: readonly PublishedCard[],
): ProvenanceFile {
  const themes: ProvenanceFile["themes"] = {};
  for (const [theme, cards] of Object.entries(file.themes)) themes[theme] = { ...cards };
  for (const entry of published) {
    themes[entry.theme] = { ...themes[entry.theme], [entry.card]: entry.provenance };
  }
  return { themes };
}

/**
 * Render the file for disk: themes and cards sorted, the readme restated,
 * trailing newline.
 *
 * Sorting is not cosmetic. The publish loop runs `SEED_CONCURRENCY` workers, so
 * completion order is neither the seed file's order nor stable between runs;
 * insertion order would turn every re-publish into a spurious diff and bury the
 * one line a reviewer is meant to see.
 */
export function serializeProvenance(file: ProvenanceFile): string {
  const themes: Record<string, Record<string, CardProvenance>> = {};
  for (const theme of Object.keys(file.themes).sort()) {
    const cards: Record<string, CardProvenance> = {};
    for (const card of Object.keys(file.themes[theme]).sort()) {
      cards[card] = file.themes[theme][card];
    }
    themes[theme] = cards;
  }
  return `${JSON.stringify({ readme: PROVENANCE_README, themes }, null, 2)}\n`;
}
