/**
 * Manual SuperGrok lane — pictures the owner generated by hand, under the subscription.
 *
 * There is no request. Grok-from-code is xAI's billed API, and this project
 * allows only providers on accounts with no payment method. The subscription
 * covers Grok in the app, on grok.com, and on X; the owner pastes the same
 * `buildPrompt` text those surfaces, saves the picture into
 * `seed-content/supergrok-drop/`, and this adapter reads it.
 *
 * `--review` is what imports. `generate()` normalises the drop file to the
 * card size and to PNG, and the runner writes those bytes to the usual
 * content-addressed review path. `--sync` then publishes that file, the same
 * way it publishes every other lane, without reading the drop folder, so a
 * picture is published only when it is the byte-for-byte reviewed file. The
 * exception is `--sync --allow-unreviewed`: a card with no review file calls
 * `generate()`, which reads the drop folder directly.
 *
 * A missing file throws `ProviderNotDrawn` rather than a failure. The bake-off
 * counts that as "not drawn", so an empty drop never looks like a lane that
 * drew badly, and it never trips the circuit breaker.
 *
 * Role is `manual`, not `lane`: the default fan-out does not include it, so a
 * review run that is not using it does not abort and does not wait on it.
 * Name it with `--providers=supergrok-manual`. No env var — there is no key,
 * and inventing one would be a place for an xAI credential to land.
 *
 * `params` is the normalisation, which changes the bytes and so is hashed into
 * the review filename. The drop path is not a parameter: it does not change
 * how a file is fitted, and putting a machine path in `params` would rename
 * every reviewed candidate when the checkout moved.
 */
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import sharp from "sharp";
import { findDropFile, SUPERGROK_DROP_DIR } from "../manual-brief";
import { finishGeneration } from "./http";
import {
  ProviderNotDrawn,
  type GeneratedImage,
  type ImageProvider,
  type ImageSizeRequest,
} from "./provider";

export interface SupergrokManualOptions {
  /** Override the drop folder. Tests point this at a fake directory. */
  dropDir?: string;
}

export function supergrokManual(opts: SupergrokManualOptions = {}): ImageProvider {
  const dropDir = opts.dropDir ?? join(process.cwd(), SUPERGROK_DROP_DIR);
  const provider: ImageProvider = {
    id: "supergrok-manual",
    role: "manual",
    format: "png",
    // Cover, never contain: a letterbox is a border, and a border is what #81
    // spent a bake-off learning not to bake into a card.
    params: { fit: "cover", encode: "png" },
    minIntervalMs: 0,
    concurrency: 4,
    requiredEnv: [],
    // Always "configured". An empty drop folder is a lane of "not drawn"
    // cells, which is the honest state — not a missing key, and not an abort.
    isConfigured: () => true,
    async generate(prompt: string, size: ImageSizeRequest): Promise<GeneratedImage> {
      const names = existsSync(dropDir)
        ? readdirSync(dropDir, { withFileTypes: true })
            .filter((entry) => entry.isFile())
            .map((entry) => entry.name)
        : [];
      const found = findDropFile(prompt, names);
      if (found.kind === "none") {
        throw new ProviderNotDrawn(
          `supergrok-manual: not drawn — no picture in ${dropDir} ending in -${found.hash}.png, .jpg, .jpeg, or .webp`,
        );
      }
      if (found.kind === "many") {
        throw new Error(
          `supergrok-manual: ${found.fileNames.length} drop files match this prompt (${found.fileNames.join(", ")}). Leave one.`,
        );
      }
      const raw = new Uint8Array(readFileSync(join(dropDir, found.fileName)));
      let fitted: Buffer;
      try {
        fitted = await sharp(raw)
          .rotate()
          .resize(size.width, size.height, { fit: "cover", position: "centre" })
          .png()
          .toBuffer();
      } catch (err) {
        throw new Error(
          `supergrok-manual: could not read ${found.fileName} as an image (${String(err)})`,
        );
      }
      // No model witness. Nothing answered an API call; recording "grok" here
      // would invent one. The sidecar stays unwitnessed, same as Cloudflare.
      return finishGeneration(provider, new Uint8Array(fitted), size);
    },
  };
  return provider;
}
