/**
 * The provider REGISTRY — the source of truth for which lanes exist (#67).
 *
 * ── Why this is code and not an env var ──────────────────────────────────────
 * #63 resolved the pipeline to an eager bake-off: every new card is generated by
 * every provider, and a human picks from a subject x provider grid. That makes
 * the composition of the lane set part of the bake-off's RESULT. If a lane were
 * selected by credential presence, forgetting to export one variable would drop
 * it silently — and the contact sheet would then show a provider with no
 * candidates, which reads as "that provider drew badly" when in fact it never
 * ran. A corrupted conclusion, on the map's first driver.
 *
 * So: the lane set is this array, diffable in a pull request. The environment
 * carries secrets and nothing else. A run may be narrowed with `--providers`,
 * which is explicit on the command line, and an unconfigured provider aborts at
 * startup before a single image is generated rather than vanishing from the run.
 *
 * ── AI Horde is deliberately absent ──────────────────────────────────────────
 * #62 shortlisted it, but #71 ("Is AI Horde acceptable for a kids' app?") is
 * open: anonymous requests are permanently shared with LAION, and censorship is
 * per-worker and non-deterministic. Registering it here would be shipping a
 * decision that ticket has not made. It is one file plus one array entry when
 * #71 clears it — which is the point of the seam.
 */
import { cloudflareSdxl } from "./cloudflare-sdxl";
import { pollinations } from "./pollinations";
import type { ImageProvider } from "./provider";

export * from "./provider";
export { pollinations } from "./pollinations";
export { cloudflareSdxl } from "./cloudflare-sdxl";

/** Every lane that exists. Adding or removing one is a reviewable code change. */
export const PROVIDERS: readonly ImageProvider[] = [pollinations(), cloudflareSdxl()];

export const PROVIDER_IDS: readonly string[] = PROVIDERS.map((p) => p.id);

/**
 * Look up a registered adapter.
 *
 * `--sync` needs this even though it never generates: it recomputes the review
 * filename's provider segment from the CURRENT adapter's params, so a param that
 * drifted since review makes the path miss and FR9 refuses the insert. The
 * registry is therefore a publish-time dependency, not only a review-time one —
 * but note it is only ever asked whether an adapter EXISTS, never whether it is
 * configured. Publishing reviewed bytes needs no credentials.
 */
export function providerById(id: string): ImageProvider | undefined {
  return PROVIDERS.find((p) => p.id === id);
}

export class ProviderSelectionError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "ProviderSelectionError";
  }
}

/**
 * Resolve the lanes a `--review` run will use, or throw with an actionable
 * message. Called before anything is generated, so a misconfigured run costs
 * nothing and writes nothing — the `DATABASE_URL` treatment, applied to keys.
 *
 * @param requested ids from `--providers=a,b`; undefined means every lane.
 */
export function selectLanes(requested?: readonly string[]): readonly ImageProvider[] {
  const known = PROVIDER_IDS.join(", ");
  let lanes = PROVIDERS;

  if (requested) {
    const unknown = requested.filter((id) => !providerById(id));
    if (unknown.length > 0) {
      throw new ProviderSelectionError(
        `--providers names ${unknown.length} unknown provider(s): ${unknown.join(", ")}.\n` +
          `   Registered: ${known}`,
      );
    }
    if (requested.length === 0) {
      throw new ProviderSelectionError(`--providers was given no ids. Registered: ${known}`);
    }
    lanes = PROVIDERS.filter((p) => requested.includes(p.id));
  }

  const unconfigured = lanes.filter((p) => !p.isConfigured());
  if (unconfigured.length > 0) {
    const detail = unconfigured
      .map((p) => `   ${p.id} — set ${p.requiredEnv.join(" and ")}`)
      .join("\n");
    const remaining = lanes.filter((p) => p.isConfigured()).map((p) => p.id);
    throw new ProviderSelectionError(
      `${unconfigured.length} provider(s) are not configured:\n${detail}\n\n` +
        `   Add the key(s) to .env.local, or narrow the run deliberately:\n` +
        `   pnpm seed --review --providers=${remaining.join(",") || "<ids>"}\n\n` +
        `   Nothing has been generated. A lane that is silently missing from a\n` +
        `   bake-off looks like a provider that drew badly, so this is an abort.`,
    );
  }
  return lanes;
}

/** Parse `--providers=a,b` from argv. Returns undefined when the flag is absent. */
export function parseProvidersFlag(argv: readonly string[]): string[] | undefined {
  const arg = argv.find((a) => a.startsWith("--providers="));
  if (arg === undefined) return undefined;
  return arg
    .slice("--providers=".length)
    .split(",")
    .map((s) => s.trim())
    .filter((s) => s.length > 0);
}
