/**
 * The provider REGISTRY — the source of truth for which lanes exist (#67).
 *
 * ── Why this is code and not an env var ──────────────────────────────────────
 * #63 resolved the pipeline to an eager bake-off: every new card is generated by
 * every provider, and a human picks from a subject x provider grid. That makes
 * the composition of the lane set part of the bake-off's RESULT. If a lane were
 * selected by credential presence, forgetting to export one variable would drop
 * it silently — and the contact sheet would then show a provider with no
 * candidates, which reads as "that provider drew badly" when in fact it never
 * ran. A corrupted conclusion, on the map's first driver.
 *
 * So: the lane set is this array, diffable in a pull request. The environment
 * carries secrets and nothing else. A run may be narrowed with `--providers`,
 * which is explicit on the command line, and an unconfigured provider aborts at
 * startup before a single image is generated rather than vanishing from the run.
 *
 * ── Lanes and escape hatches ─────────────────────────────────────────────────
 * #71 resolved AI Horde to "keyed and wired, but NOT a bake-off lane", and made
 * expressing that this seam's job. So `role` splits the registry: the default
 * fan-out is the lanes, while an escape hatch is reachable only by naming it.
 * Everything else about a hatch is identical — `--sync` resolves it, and its
 * candidates are named the same way — because a card published from the hatch
 * must be as traceable as any other.
 *
 * ── AI Horde, and why its model is in code rather than in the environment ────
 * #71 settled its request parameters (`slow_workers: true` mandatory,
 * `allow_downgrade` never set, `replacement_filter: false`) but explicitly left
 * the model to #74. #74 pinned it, so the hatch registers here.
 *
 * The model lives in `ai-horde.ts` and NOT in `AIHORDE_MODEL`, for this file's
 * own reason one level down. The environment carries secrets; anything that
 * changes the BYTES belongs in a diff. A model name changes the bytes twice
 * over: `params` is hashed into the review filename, so an env-driven model
 * would silently rename every reviewed candidate when someone edited their
 * `.env.local` — and on this provider a mistyped name is not a 404 but a
 * DIFFERENT model, with the horde's most-served models being NSFW ones.
 */
import { aiHorde } from "./ai-horde";
import { cloudflareSdxl } from "./cloudflare-sdxl";
import { pollinations } from "./pollinations";
import type { ImageProvider } from "./provider";

export * from "./provider";
export { pollinations } from "./pollinations";
export { cloudflareSdxl } from "./cloudflare-sdxl";
export { aiHorde } from "./ai-horde";

/** Every provider that exists. Adding or removing one is a reviewable code change. */
export const PROVIDERS: readonly ImageProvider[] = [pollinations(), cloudflareSdxl(), aiHorde()];

/** Array of all registered provider IDs. */
export const PROVIDER_IDS: readonly string[] = PROVIDERS.map((p) => p.id);

/** The default fan-out: bake-off lanes only, escape hatches excluded (#71). */
export const LANES: readonly ImageProvider[] = PROVIDERS.filter((p) => p.role === "lane");

/**
 * Look up a registered adapter.
 *
 * `--sync` needs this even though it never generates: it recomputes the review
 * filename's provider segment from the CURRENT adapter's params, so a param that
 * drifted since review makes the path miss and FR9 refuses the insert. The
 * registry is therefore a publish-time dependency, not only a review-time one —
 * but note it is only ever asked whether an adapter EXISTS, never whether it is
 * configured. Publishing reviewed bytes needs no credentials.
 */
export function providerById(id: string): ImageProvider | undefined {
  return PROVIDERS.find((p) => p.id === id);
}

/** Error thrown when provider selection or configuration fails during seeding. */
export class ProviderSelectionError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "ProviderSelectionError";
  }
}

/**
 * Resolve the lanes a `--review` run will use, or throw with an actionable
 * message. Called before anything is generated, so a misconfigured run costs
 * nothing and writes nothing — the `DATABASE_URL` treatment, applied to keys.
 *
 * Naming a provider explicitly reaches an escape hatch too — that IS how #71
 * intends the hatch to be invoked, for cards the lanes refused or drew badly.
 * The role only decides the DEFAULT set.
 *
 * @param requested ids from `--providers=a,b`; undefined means every lane.
 * @param registry defaults to the real one; injectable so the escape-hatch path
 *   is testable before an escape hatch is registered.
 */
export function selectLanes(
  requested?: readonly string[],
  registry: readonly ImageProvider[] = PROVIDERS,
): readonly ImageProvider[] {
  const known = registry.map((p) => p.id).join(", ");
  let lanes = registry.filter((p) => p.role === "lane");

  if (requested) {
    const unknown = requested.filter((id) => !registry.some((p) => p.id === id));
    if (unknown.length > 0) {
      throw new ProviderSelectionError(
        `--providers names ${unknown.length} unknown provider(s): ${unknown.join(", ")}.\n` +
          `   Registered: ${known}`,
      );
    }
    if (requested.length === 0) {
      throw new ProviderSelectionError(`--providers was given no ids. Registered: ${known}`);
    }
    lanes = registry.filter((p) => requested.includes(p.id));
  }

  const unconfigured = lanes.filter((p) => !p.isConfigured());
  if (unconfigured.length > 0) {
    const detail = unconfigured
      .map((p) => `   ${p.id} — set ${p.requiredEnv.join(" and ")}`)
      .join("\n");
    const remaining = lanes.filter((p) => p.isConfigured()).map((p) => p.id);
    throw new ProviderSelectionError(
      `${unconfigured.length} provider(s) are not configured:\n${detail}\n\n` +
        `   Add the key(s) to .env.local, or narrow the run deliberately:\n` +
        `   pnpm seed --review --providers=${remaining.join(",") || "<ids>"}\n\n` +
        `   Nothing has been generated. A lane that is silently missing from a\n` +
        `   bake-off looks like a provider that drew badly, so this is an abort.`,
    );
  }
  return lanes;
}

/** Parse `--providers=a,b` from argv. Returns undefined when the flag is absent. */
export function parseProvidersFlag(argv: readonly string[]): string[] | undefined {
  const arg = argv.find((a) => a.startsWith("--providers="));
  if (arg === undefined) return undefined;
  return arg
    .slice("--providers=".length)
    .split(",")
    .map((s) => s.trim())
    .filter((s) => s.length > 0);
}
